#!/usr/bin/env bash
#configure web-02 to be identical with web-01
#with automated bash script
#add nginx response header
#track the activities of load balancer 

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
sudo touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default server
    add_header X-Served-By $HOSTNAME;
    root /etc/nginx/html;
    index  index.html.index.html
    location /redirect_me {
          return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
  }
  error_page 404 /404.html;
 location /404 {
   root /etc/nginx/html;
   internal;
}" > /etc/nginx/sites-available/default
sudo service nginx restart
