#!/usr/bin/env bash
#Installs and configures HAproxy in a load balancer server

apt-get update
apt-get -y install haproxy

echo "
frontend http
    bind *:80
    mode http
    default_backend web-servers

backend web-servers
    mode http
    balance roundrobin
    server 176031-web-01 35.175.126.206 check
    server 176031-web-100.25.109.142 check
" >> /etc/haproxy/haproxy.cfg

# Make sure HAProxy can be managed via an init script
systemctl enable haproxy.service
systemctl start haproxy.service
