#!/usr/bin/env bash

service nginx stop

# Update the Nginx configuration to run as the nginx user
sed -i "s/user\s*www-data;/user nginx;/" /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
# Update the Nginx configuration to listen on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill -9 apache2
sudo -u nginx service nginx start
