#!/usr/bin/env bash

service nginx stop

# Update the Nginx configuration to run as the nginx user
sed -i "s/user\s*nginx;/user nginx;/g" /etc/nginx/nginx.conf

# Update the Nginx configuration to listen on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

service nginx start
