#!/usr/bin/env bash

# Update the Nginx configuration to run as the nginx user
chmod 777 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Update the Nginx configuration to listen on port 8080
sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-available/default /etc/nginx/sites-available/default
pkill -9 apache2
# Start the Nginx service
sudo -u nginx service nginx restart
